stages:
  afew-extract-wav:
    cmd: python preprocess/AFEW_to_wav.py
    deps:
      - ${afew_raw}
      - preprocess
    outs:
      - ${afew_wav}
  extract-mfcc-features:
    cmd: python preprocess/mfcc_features.py
    deps:
      - ${afew_wav}
      - ${tess_wav}
      - preprocess
    outs:
      - ${afew_mfcc}
      - ${tess_mfcc}
