stages:
  afew-extract-wav:
    cmd: python ${data.script.afew_wav}
    deps:
      - ${data.script.afew_wav}
      - ${data.datasets.afew.video}
    outs:
      - ${data.datasets.afew.wav}
    params:
      - data.datasets.afew
      - data.script.afew_wav
  extract-features:
    foreach: ${data.extraction}
    do:
      cmd: python ${data.script.features} -f ${item.name} -d ${item.dataset} -i ${item.in_path} -o ${item.out_path} -x ${item.index}
      deps:
        - ${item.in_path}
        - ${data.script.features}
      outs:
        - ${item.out_path}
        - ${item.index}
      params:
        - data.script.features
        - data.extraction
  update-global-index:
    cmd: python ${data.script.global_index}
    deps:
      - ${data.index_dir}
    outs:
      - ${data.global_index_dir}
    params:
      - data.index_dir
      - data.global_index_dir
      - data.script.global_index
  train:
    foreach: ${train.training}
    do:
      cmd: python ${train.script.train} -m ${item.model} -f ${item.features} -w ${item.window_size} -o ${item.out_file}
      deps:
        - ${train.script.train}
      outs:
        - ${item.out_file}
      params:
        - train
  analysis:
    cmd: python ${analysis.script.analyze}
    deps:
      - ${train.results_dir}
    outs:
      - ${analysis.plots}
      - ${analysis.tables}
