data:
  data_dir: data
  datasets:
    afew:
      video: data/AFEW
      wav: data/AFEW_WAV
    tess:
      wav: data/TESS
  emotions:
  - angry
  - disgust
  - fear
  - happy
  - neutral
  - sad
  - surprise
  extraction:
  - dataset: afew
    in_path: data/AFEW_WAV
    index: data/index/afew_mfcc
    name: mfcc
    out_path: data/afew_mfcc
  - dataset: afew
    in_path: data/AFEW_WAV
    index: data/index/afew_lpcc
    name: lpcc
    out_path: data/afew_lpcc
  - dataset: afew
    in_path: data/AFEW_WAV
    index: data/index/afew_lfcc
    name: lfcc
    out_path: data/afew_lfcc
  - dataset: tess
    in_path: data/TESS
    index: data/index/tess_mfcc
    name: mfcc
    out_path: data/tess_mfcc
  - dataset: tess
    in_path: data/TESS
    index: data/index/tess_lpcc
    name: lpcc
    out_path: data/tess_lpcc
  - dataset: tess
    in_path: data/TESS
    index: data/index/tess_lfcc
    name: lfcc
    out_path: data/tess_lfcc
  features:
  - mfcc
  - lpcc
  - lfcc
  features_dir: data
  global_index: data/global_index
  index_dir: data/index
  script:
    afew_wav: preprocess/AFEW_to_wav.py
    features: preprocess/extract_features.py
    global_index: preprocess/combine_index.py
train:
  folds: 5
  window_size: 48
