afew_raw: 'data/AFEW'
afew_wav: 'data/AFEW_wav'
afew_mfcc: 'data/AFEW_MFCC'
afew_lpcc: 'data/AFEW_LPCC'
afew_lfpc: 'data/AFEW_LFPC'

tess_wav: 'data/TESS'
tess_mfcc: 'data/TESS_MFCC'
tess_lpcc: 'data/TESS_LPCC'
tess_lfpc: 'data/TESS_LFPC'
tess_split: 'data/tess_split.pkl'

train:
  window_size: 48
  folds: 5
